#include "../src/gaConfiguration.hpp"
#include "../src/gaCsvRecorder.hpp"
#include "../src/gaParameterTable.hpp"
#include "../src/geneticAlgorithm.hpp"
#include "../src/group.hpp"

#include "../src/copySelect/copySelect.hpp"
#include "../src/copySelect/dmsxfSelect.hpp"
#include "../src/copySelect/randomSelectWithoutReplacement.hpp"
#include "../src/copySelect/rankingSelect.hpp"
#include "../src/copySelect/rouletteSelect.hpp"
#include "../src/copySelect/stairsSelect.hpp"

#include "../src/crossover/blockCrossover.hpp"
#include "../src/crossover/blockCrossoverWithDmsxf.hpp"
#include "../src/crossover/crossover.hpp"
#include "../src/crossover/embeddMap.hpp"
#include "../src/crossover/embeddPartialGraph.hpp" 
#include "../src/crossover/generateEmbeddMap.hpp"
#include "../src/crossover/generateFlexibleBlockEmbeddMap.hpp"
#include "../src/crossover/generateOrthogonalBlockEmbeddMap.hpp"

#include "../src/initialize/initialize.hpp"
#include "../src/initialize/neighborInitialize.hpp"
#include "../src/initialize/randomInitialize.hpp"

#include "../src/mutate/lambdaChangeMutate.hpp"
#include "../src/mutate/mutate.hpp"
#include "../src/mutate/twoChangeMutate.hpp"

#include "../src/survivorSelect/elitistSelect.hpp"
#include "../src/survivorSelect/mixSelect.hpp"
#include "../src/survivorSelect/passAllChild.hpp"
#include "../src/survivorSelect/rankingSelect.hpp"
#include "../src/survivorSelect/survivorSelect.hpp"
