SOURCES = test.cpp
COMPILE_OPTION = -O3 -mtune=native -march=native
LIB = -L /usr/local/lib -L ../../lib -lgtest -lgtest_main -lpthread -lodpGridGraphs

main: 
	g++ $(SOURCES) $(COMPILE_OPTION) $(LIB) -o test